---

- name: customize docker-compose.override.yml
  template:
    src: docker-compose.override.yml.j2
    dest: '{{ project_path }}/deployment/docker-compose.override.yml'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: customize backup
  template:
    src: 'sftp_backup/{{ item.template }}'
    dest: '{{ project_path }}/deployment/{{ item.dest }}'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
  with_items:
    - { 'template': 'sftp_pg_credential.env.j2', dest: 'sftp_pg_credential.env'}
    - { 'template': 'sftp_media_credential.env.j2', dest: 'sftp_media_credential.env'}

- name: customize inaware credentials
  template:
    src: inaware_credential.env.j2
    dest: '{{ project_path }}/deployment/inaware_credential.env'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"

- name: customize geonode credentials
  template:
    src: geonode_credential.env.j2
    dest: '{{ project_path }}/deployment/geonode_credential.env'
    owner: '{{ remote_user }}'
    group: '{{ remote_group }}'
    mode: "u=rw,g=rw,o=r"
